services:
  - type: web
    name: soil-nutrition-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false   # isi manual di dashboard Render
      - key: JWT_SECRET
        sync: false   # isi manual di dashboard Render
      - key: FRONTEND_URL
        sync: false   # isi URL Vercel setelah deploy frontend
